name: helper
author: Luck
version: "${version}"
description: "Helper"
main: me.lucko.helper.internal.StandalonePlugin
website: https://github.com/lucko/helper
load: STARTUP
softdepend: [ProtocolLib]
folia-supported: true
api-version: 1.13
